name: Commit
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Patch
        run: patch ${{ github.workspace }}/coredns/plugin.cfg -i ${{ github.workspace }}/plugin.cfg.patch
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
          stable: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Make
        run: make
        working-directory: ${{ github.workspace }}/coredns
